compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  gradient_accumulation_steps: 1  # Consider increasing if still facing memory issues
  offload_optimizer_device: none  # Changed from 'cpu' to 'none'
  offload_param_device: none      # Changed from 'cpu' to 'none'
  zero3_init_flag: true           # Changed from 'false' to 'true'
  zero_stage: 3                   # Changed from '2' to '3'
  max_split_size_mb: 512          # Reduced from '1024' to '512'
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: 'bf16'
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false